version: "3"
services:
        jenkins:
                container_name: jenkins
                user: "${UID}:${GID}"
                image: jenkins/jenkins
                ports:
                        - "8080:8080"
                volumes:
                        - "$PWD/jenkins:/var/jenkins_home"
                networks:
                        - net
        remote:
                container_name: remote
                image: remote
                build: .
        db_host:
                container_name: db
                image: mysql:5.7
                environment: 
                        - "MYSQL_ROOT_PASSWORD=dipto"
                volumes: 
                        - "$PWD/db_data:/var/lib/mysql"
                
                        

