version: "3"
services:
        jenkins:
                container_name: jenkins
                image: jenkins/jenkins
                ports:
                        - "8080:8080"
                volumes:
                        - "$PWD/jenkins:/var/jenkins_home"
                networks:
                        - net
        remote:
                container_name: : remote
                image: remote
                build: .
                        

